import React from 'react';
import { FlexBox, Title, Text, Button, ObjectStatus } from '@ui5/webcomponents-react';
import type { Engagement, TechRecommendation } from '../types';
import type { Experiment, RunRecord, DatasetRecord } from '../../synthetic-data-v2/types';
import { SP, getFieldAccess } from '../../synthetic-data-v2/constants';

interface Props {
  engagement: Engagement;
  recommendation: TechRecommendation | null;
  experiment: Experiment | null;
  runs: RunRecord[];
  datasets: DatasetRecord[];
}

export function generateHandoffMarkdown(
  engagement: Engagement,
  recommendation: TechRecommendation | null,
  experiment: Experiment | null,
  runs: RunRecord[],
  datasets: DatasetRecord[],
): string {
  const expRuns = runs.filter(r => r.experimentId === experiment?.id && r.status === 'Completed');
  const bestRun = expRuns.length > 0
    ? expRuns.reduce((b, r) => (r.metrics.f1 ?? 0) > (b.metrics.f1 ?? 0) ? r : b)
    : null;
  const dataset = datasets.find(d => d.id === engagement.currentDatasetId);

  const lines: string[] = [
    `# Engineering Handoff`,
    `## ${engagement.name}`,
    ``,
    `**Customer:** ${engagement.customer}`,
    `**Use Case:** ${engagement.useCaseName || '—'}`,
    `**Prepared:** ${new Date().toISOString().slice(0, 10)}`,
    ``,
    `---`,
    ``,
    `## Business Problem`,
    ``,
    engagement.businessProblem,
    ``,
  ];

  if (recommendation) {
    lines.push(
      `## Business Question`,
      ``,
      `> "${recommendation.businessQuestion}"`,
      ``,
      `## Recommended Approach`,
      ``,
      `**Experiment Type:** ${recommendation.taskType}`,
      ``,
      recommendation.taskTypeExplanation,
      ``,
      `**Target:** \`${recommendation.target}\` — ${recommendation.targetStatus}`,
      ``,
      recommendation.targetExplanation,
      ``,
      `## Data Requirements`,
      ``,
      ...recommendation.informationFields.map(f =>
        `- \`${f.name}\` (${f.category}) — ${f.description} [${f.available ? '✓ Available' : '⚠ Not yet available'}]`
      ),
      ``,
      `## Data Access`,
      ``,
      `> Mappings marked Candidate are illustrative. Confirm with SAP product team before production use.`,
      ``,
      `| Signal | Why Needed | SAP Product | Access Method | Status |`,
      `|---|---|---|---|---|`,
      ...recommendation.informationFields.map(f => {
        const access = getFieldAccess(f.name);
        return `| \`${f.name}\` | ${f.description} | ${access?.sapProduct ?? f.sapProduct ?? '—'} | ${access?.accessMethod ?? f.accessNote ?? '—'} | ${access?.status ?? f.accessStatus ?? '—'} |`;
      }),
      ``,
    );
  }

  if (experiment) {
    lines.push(
      `## Experiment Configuration`,
      ``,
      `**Experiment:** ${experiment.name}`,
      `**Pack Version:** ${experiment.packVersion}`,
      `**Task Type:** ${experiment.taskType}`,
      `**Target:** ${experiment.target}`,
      `**Approaches Tested:** ${experiment.approachIds.join(', ')}`,
      ``,
    );
  }

  if (dataset) {
    lines.push(
      `## Dataset`,
      ``,
      `**Name:** ${dataset.name}`,
      `**Fidelity:** ${dataset.fidelityLevel}`,
      `**Quality:** ${dataset.qualityStatus}`,
      `**Records:** ${Object.entries(dataset.recordCounts).map(([k, v]) => `${k}: ${v.toLocaleString()}`).join(', ')}`,
      `**Lineage:** ${dataset.lineage}`,
      ``,
    );
  }

  if (expRuns.length > 0) {
    lines.push(`## Experiment Results`, ``);
    lines.push(`| Approach | F1 | AUC | Recall | Precision | Runtime |`);
    lines.push(`|---|---|---|---|---|---|`);
    expRuns.forEach(r => {
      lines.push(`| ${r.approachId} | ${(r.metrics.f1 ?? 0).toFixed(2)} | ${(r.metrics.auc ?? 0).toFixed(2)} | ${(r.metrics.recall ?? 0).toFixed(2)} | ${(r.metrics.precision ?? 0).toFixed(2)} | ${r.runtime} |`);
    });
    lines.push(``);

    if (bestRun) {
      lines.push(
        `**Leading Candidate:** ${bestRun.approachId} (F1: ${(bestRun.metrics.f1 ?? 0).toFixed(2)}, AUC: ${(bestRun.metrics.auc ?? 0).toFixed(2)})`,
        ``,
      );
    }
  }

  if (recommendation) {
    lines.push(
      `## Engineering Discussion Points`,
      ``,
      ...recommendation.engineeringQuestions.map(q => `- ${q}`),
      ``,
      `## Next Steps`,
      ``,
      `- [ ] Validate target definition with customer data team`,
      `- [ ] Confirm data availability for behavioral features (90-day history minimum)`,
      `- [ ] Run experiments against approved customer data sample before production model selection`,
      `- [ ] Define production integration pattern (batch scoring vs. real-time)`,
      recommendation.confidence !== 'High'
        ? `- [ ] Address recommendation confidence gaps before proceeding`
        : '',
    ).filter(Boolean);
  }

  lines.push(``, `---`, `*Generated by SAP Synthetic Data Accelerator v3*`);
  return lines.join('\n');
}

export function generateDataAccessCSV(
  recommendation: TechRecommendation | null,
  engagementName: string,
): string {
  if (!recommendation) return '';
  const headers = ['Entity', 'Field', 'Business Meaning', 'Required By', 'Category', 'Dataset Available', 'SAP Product', 'Source Object', 'Access Method', 'API/Service', 'Operation', 'Status', 'Notes'];
  const rows = recommendation.informationFields.map(f => {
    const access = getFieldAccess(f.name);
    return [
      access?.entity ?? '—',
      f.name,
      f.description,
      engagementName,
      f.category,
      f.available ? 'Yes' : 'No',
      access?.sapProduct ?? f.sapProduct ?? '—',
      access?.sourceObject ?? '—',
      access?.accessMethod ?? f.accessNote ?? '—',
      access?.apiService ?? '—',
      access?.operation ?? '—',
      access?.status ?? f.accessStatus ?? '—',
      access?.notes ?? 'Illustrative mapping — confirm with SAP product team',
    ].map(v => typeof v === 'string' && v.includes(',') ? `"${v}"` : String(v ?? '')).join(',');
  });
  return [headers.join(','), ...rows].join('\n');
}

const EngineeringHandoff: React.FC<Props> = ({ engagement, recommendation, experiment, runs, datasets }) => {
  const expRuns = runs.filter(r => r.experimentId === experiment?.id && r.status === 'Completed');
  const bestRun = expRuns.length > 0
    ? expRuns.reduce((b, r) => (r.metrics.f1 ?? 0) > (b.metrics.f1 ?? 0) ? r : b)
    : null;
  const dataset = datasets.find(d => d.id === engagement.currentDatasetId);

  const section = (title: string, children: React.ReactNode) => (
    <div style={{ marginBottom: SP.l }}>
      <div style={{ borderBottom: '2px solid var(--sapHighlightColor)', paddingBottom: SP.xs, marginBottom: SP.s }}>
        <Title level="H4" style={{ color: 'var(--sapHighlightColor)' }}>{title}</Title>
      </div>
      {children}
    </div>
  );

  const row = (label: string, value: React.ReactNode) => (
    <FlexBox style={{ marginBottom: SP.xs, gap: SP.m }}>
      <Text style={{ fontWeight: 600, minWidth: 160, color: 'var(--sapContent_LabelColor)', fontSize: '0.875rem' }}>{label}</Text>
      <Text style={{ fontSize: '0.875rem' }}>{value}</Text>
    </FlexBox>
  );

  return (
    <div style={{
      fontFamily: 'var(--sapFontFamily)',
      color: 'var(--sapTextColor)',
      lineHeight: 1.6,
    }}>
      {section('Engagement Summary', (
        <>
          {row('Customer', engagement.customer)}
          {row('Use Case', engagement.useCaseName || '—')}
          {row('Prepared', new Date().toISOString().slice(0, 10))}
        </>
      ))}

      {section('Business Problem', (
        <Text style={{ lineHeight: 1.7 }}>{engagement.businessProblem}</Text>
      ))}

      {recommendation && section('Business Question', (
        <>
          <div style={{ borderLeft: `3px solid var(--sapHighlightColor)`, paddingLeft: SP.m, marginBottom: SP.s }}>
            <Text style={{ fontSize: '1rem', fontStyle: 'italic' }}>"{recommendation.businessQuestion}"</Text>
          </div>
          {row('Experiment Type', recommendation.taskType)}
          {row('Target', (
            <FlexBox gap={SP.xs} alignItems="Center">
              <code style={{ fontFamily: 'monospace', fontSize: '0.875rem' }}>{recommendation.target}</code>
              <ObjectStatus state={recommendation.targetStatus === 'Available' ? 'Positive' : recommendation.targetStatus === 'Derivable' ? 'Information' : 'Critical'}>
                {recommendation.targetStatus}
              </ObjectStatus>
            </FlexBox>
          ))}
        </>
      ))}

      {recommendation && section('Data Requirements', (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          {recommendation.informationFields.map(f => (
            <FlexBox key={f.name} gap={SP.s} alignItems="flex-start">
              <Text style={{ fontSize: '0.875rem', color: f.available ? 'var(--sapPositiveColor)' : 'var(--sapCriticalColor)', minWidth: 16 }}>
                {f.available ? '✓' : '⚠'}
              </Text>
              <div>
                <code style={{ fontFamily: 'monospace', fontSize: '0.8125rem' }}>{f.name}</code>
                <Text style={{ fontSize: '0.8125rem', color: 'var(--sapContent_LabelColor)', marginLeft: 8 }}>
                  — {f.description} {!f.available && '(not yet available)'}
                </Text>
              </div>
            </FlexBox>
          ))}
        </div>
      ))}

      {dataset && section('Dataset', (
        <>
          {row('Name', dataset.name)}
          {row('Fidelity', <ObjectStatus state="Information">{dataset.fidelityLevel}</ObjectStatus>)}
          {row('Quality', dataset.qualityStatus)}
          {row('Records', Object.entries(dataset.recordCounts).map(([k, v]) => `${k}: ${v.toLocaleString()}`).join(' · '))}
          {row('Lineage', dataset.lineage)}
        </>
      ))}

      {expRuns.length > 0 && section('Experiment Results', (
        <>
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.875rem' }}>
              <thead>
                <tr style={{ background: 'var(--sapList_HeaderBackground)' }}>
                  {['Approach', 'F1', 'AUC', 'Recall', 'Precision', 'Runtime'].map(h => (
                    <th key={h} style={{ padding: '6px 12px', textAlign: 'left', fontWeight: 700, borderBottom: '2px solid var(--sapGroup_TitleBorderColor)' }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {expRuns.map((r, i) => (
                  <tr key={r.id} style={{ background: i % 2 === 0 ? 'transparent' : 'var(--sapField_Background)' }}>
                    <td style={{ padding: '6px 12px', fontWeight: r.id === bestRun?.id ? 700 : 400 }}>{r.approachId}</td>
                    <td style={{ padding: '6px 12px' }}>{(r.metrics.f1 ?? 0).toFixed(2)}</td>
                    <td style={{ padding: '6px 12px' }}>{(r.metrics.auc ?? 0).toFixed(2)}</td>
                    <td style={{ padding: '6px 12px' }}>{(r.metrics.recall ?? 0).toFixed(2)}</td>
                    <td style={{ padding: '6px 12px' }}>{(r.metrics.precision ?? 0).toFixed(2)}</td>
                    <td style={{ padding: '6px 12px' }}>{r.runtime}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {bestRun && (
            <Text style={{ marginTop: SP.s, fontWeight: 600 }}>
              Leading candidate: {bestRun.approachId} (F1: {(bestRun.metrics.f1 ?? 0).toFixed(2)}, AUC: {(bestRun.metrics.auc ?? 0).toFixed(2)})
            </Text>
          )}
        </>
      ))}

      {recommendation && section('Engineering Discussion Points', (
        <ul style={{ margin: 0, paddingLeft: SP.l }}>
          {recommendation.engineeringQuestions.map((q, i) => (
            <li key={i} style={{ marginBottom: SP.xs }}><Text style={{ lineHeight: 1.6 }}>{q}</Text></li>
          ))}
        </ul>
      ))}

      {recommendation && section('Data Access', (
        <>
          <Text style={{ display: 'block', fontSize: '0.8125rem', fontStyle: 'italic', color: 'var(--sapContent_LabelColor)', marginBottom: SP.s }}>
            Illustrative mappings only — confirm with SAP product team before production use.
          </Text>
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.875rem' }}>
              <thead>
                <tr style={{ background: 'var(--sapList_HeaderBackground)' }}>
                  {['Signal', 'Why Needed', 'SAP Product', 'Access Method', 'Status'].map(h => (
                    <th key={h} style={{ padding: '6px 12px', textAlign: 'left', fontWeight: 700, borderBottom: '2px solid var(--sapGroup_TitleBorderColor)', fontSize: '0.8125rem' }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {recommendation.informationFields.map((f, i) => {
                  const access = getFieldAccess(f.name);
                  const statusColors: Record<string, string> = { 'Candidate': 'var(--sapInformationColor)', 'Customer-Specific': 'var(--sapCriticalColor)', 'Unresolved': 'var(--sapNegativeColor)', 'Validated': 'var(--sapPositiveColor)' };
                  const status = access?.status ?? f.accessStatus ?? '—';
                  return (
                    <tr key={f.name} style={{ background: i % 2 === 0 ? 'transparent' : 'var(--sapField_Background)', borderBottom: '1px solid var(--sapGroup_TitleBorderColor)' }}>
                      <td style={{ padding: '5px 12px' }}><code style={{ fontFamily: 'monospace', fontSize: '0.8rem' }}>{f.name}</code></td>
                      <td style={{ padding: '5px 12px', fontSize: '0.8125rem', color: 'var(--sapContent_LabelColor)' }}>{f.description}</td>
                      <td style={{ padding: '5px 12px', fontSize: '0.8125rem', color: 'var(--sapContent_LabelColor)' }}>{access?.sapProduct ?? f.sapProduct ?? '—'}</td>
                      <td style={{ padding: '5px 12px', fontSize: '0.8125rem', color: 'var(--sapContent_LabelColor)' }}>{access?.accessMethod ?? f.accessNote ?? '—'}</td>
                      <td style={{ padding: '5px 12px' }}>
                        {status !== '—' ? (
                          <span style={{ display: 'inline-block', padding: '1px 7px', borderRadius: 10, fontSize: '0.75rem', fontWeight: 700, background: `${statusColors[status] ?? 'var(--sapContent_LabelColor)'}22`, color: statusColors[status] ?? 'var(--sapContent_LabelColor)' }}>
                            {status}
                          </span>
                        ) : <Text style={{ fontSize: '0.8125rem', color: 'var(--sapContent_LabelColor)' }}>—</Text>}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </>
      ))}

      {section('Next Steps', (
        <ul style={{ margin: 0, paddingLeft: SP.l }}>
          {[
            'Validate target definition with customer data team',
            'Confirm data availability for behavioral features (90-day history minimum)',
            'Run experiments against approved customer data sample before production model selection',
            'Define production integration pattern (batch scoring vs. real-time)',
          ].map((s, i) => (
            <li key={i} style={{ marginBottom: SP.xs }}>
              <FlexBox gap={SP.s} alignItems="flex-start">
                <input type="checkbox" style={{ marginTop: 3, accentColor: 'var(--sapHighlightColor)' }} />
                <Text style={{ lineHeight: 1.5 }}>{s}</Text>
              </FlexBox>
            </li>
          ))}
        </ul>
      ))}
    </div>
  );
};

export default EngineeringHandoff;
