#!/usr/bin/env python3
"""Regenerate dashboard/data.js and the encrypted public build from the latest run.

Reads:  data/history/*.json (all runs), data/portfolio.json,
        data/dashboard_password.txt (for the public build)
Writes: dashboard/data.js               (plaintext, local viewing)
        dashboard/public/*              (password-protected GitHub Pages build)

The scoreboard rolls up every pick from every historical run and refreshes
last prices via yfinance so past picks show performance-since-pick.

Usage: python scripts/publish.py
"""

import base64
import hashlib
import json
import os
import shutil
import datetime as dt
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
HISTORY = DATA / "history"
DASH = ROOT / "dashboard"
PUBLIC = DASH / "public"
OUT = DASH / "data.js"
PASSWORD_FILE = DATA / "dashboard_password.txt"  # local-only, gitignored
KEY_FILE = DATA / "dashboard_key.txt"  # committed: salt + PBKDF2-derived AES key (not the password)
PBKDF2_ITERATIONS = 200_000


def fetch_quotes(tickers: list[str]) -> dict[str, float]:
    if not tickers:
        return {}
    import yfinance as yf
    px = yf.download(sorted(set(tickers)), period="5d", auto_adjust=True, progress=True)["Close"]
    quotes = {}
    if hasattr(px, "columns"):
        for t in px.columns:
            s = px[t].dropna()
            if not s.empty:
                quotes[t] = round(float(s.iloc[-1]), 2)
    else:  # single ticker -> Series
        s = px.dropna()
        if not s.empty:
            quotes[tickers[0]] = round(float(s.iloc[-1]), 2)
    return quotes


def main() -> None:
    runs = sorted(HISTORY.glob("*.json"))
    if not runs:
        raise SystemExit("No history files in data/history/ — nothing to publish")
    latest = json.loads(runs[-1].read_text(encoding="utf-8"))

    portfolio = {"positions": []}
    if (DATA / "portfolio.json").exists():
        portfolio = json.loads((DATA / "portfolio.json").read_text(encoding="utf-8"))

    # Every ticker whose latest price we need
    all_picks = []  # (date, pick) newest run first
    for run_file in reversed(runs):
        run = json.loads(run_file.read_text(encoding="utf-8"))
        for p in run.get("picks", []):
            all_picks.append((run.get("week", run_file.stem), p))
    tickers = [p["ticker"] for _, p in all_picks] + [
        pos["ticker"].upper() for pos in portfolio.get("positions", [])
    ]
    print(f"Refreshing quotes for {len(set(tickers))} tickers...")
    quotes = fetch_quotes(tickers)

    # Holdings verdicts from the latest run
    verdicts = {h["ticker"].upper(): h for h in latest.get("holdingsReview", [])}
    portfolio_rows = []
    for pos in portfolio.get("positions", []):
        t = pos["ticker"].upper()
        v = verdicts.get(t, {})
        portfolio_rows.append({
            "ticker": t,
            "shares": pos["shares"],
            "costBasis": pos["cost_basis"],
            "buyDate": pos.get("buy_date"),
            "lastPrice": quotes.get(t, v.get("lastPrice")),
            "verdict": v.get("verdict"),
            "verdictReason": v.get("verdictReason"),
        })

    scoreboard = [{
        "datePicked": date,
        "ticker": p["ticker"],
        "rating": p.get("rating"),
        "priceAtPick": p.get("price"),
        "lastPrice": quotes.get(p["ticker"], p.get("price")),
    } for date, p in all_picks]

    data = {
        "week": latest.get("week"),
        "generated": latest.get("generated"),
        "pricesAsOf": dt.date.today().isoformat(),
        "picks": latest.get("picks", []),
        "portfolio": portfolio_rows,
        "scoreboard": scoreboard,
    }
    OUT.write_text(
        "/* Regenerated by the weekly agent - do not edit by hand. */\n"
        "window.DASHBOARD_DATA = " + json.dumps(data, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} (week {data['week']}, {len(data['picks'])} picks, "
          f"{len(portfolio_rows)} holdings, {len(scoreboard)} scoreboard rows)")
    build_public(data)


def load_key():
    """Return (salt, aes_key) for the public build.

    Preferred source is KEY_FILE ("v1:<salt_b64>:<key_b64>"), which holds the
    PBKDF2-derived key so the actual password never has to be in the repo.
    If only the local PASSWORD_FILE exists, derive the key from it once and
    write KEY_FILE so subsequent (incl. cloud-agent) runs can encrypt.
    The salt is embedded in the payload; the browser re-derives the same key
    from the user's typed password + that salt (gate.js)."""
    if KEY_FILE.exists():
        _, salt_b64, key_b64 = KEY_FILE.read_text(encoding="utf-8").strip().split(":")
        return base64.b64decode(salt_b64), base64.b64decode(key_b64)
    if PASSWORD_FILE.exists():
        password = PASSWORD_FILE.read_text(encoding="utf-8").strip()
        salt = os.urandom(16)
        key = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, PBKDF2_ITERATIONS, dklen=32)
        b64 = lambda b: base64.b64encode(b).decode()
        KEY_FILE.write_text(f"v1:{b64(salt)}:{b64(key)}\n", encoding="utf-8")
        print(f"Derived {KEY_FILE.name} from {PASSWORD_FILE.name} (commit the key file; keep the password file local)")
        return salt, key
    return None


def build_public(data: dict) -> None:
    """Build dashboard/public/: same dashboard but with AES-encrypted data
    behind a password gate, suitable for publishing on GitHub Pages."""
    loaded = load_key()
    if loaded is None:
        print(f"No {KEY_FILE.name} or {PASSWORD_FILE.name} — skipping public build")
        return
    salt, key = loaded
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    iv = os.urandom(12)
    ciphertext = AESGCM(key).encrypt(iv, json.dumps(data).encode(), None)

    PUBLIC.mkdir(exist_ok=True)
    b64 = lambda b: base64.b64encode(b).decode()
    (PUBLIC / "data.enc.js").write_text(
        "/* Encrypted dashboard payload - decrypted client-side by gate.js. */\n"
        "window.ENCRYPTED_DASHBOARD = " + json.dumps({
            "v": 1, "iter": PBKDF2_ITERATIONS,
            "salt": b64(salt), "iv": b64(iv), "ct": b64(ciphertext),
        }) + ";\n",
        encoding="utf-8",
    )
    shutil.copy(DASH / "public_index.html", PUBLIC / "index.html")
    for name in ("style.css", "app.js", "trade.js", "gate.js"):
        shutil.copy(DASH / name, PUBLIC / name)
    (PUBLIC / ".nojekyll").touch()
    print(f"Wrote encrypted public build to {PUBLIC}")


if __name__ == "__main__":
    main()
