#!/usr/bin/env python3
"""Regenerate dashboard/data.js from the latest weekly run.

Reads:  data/history/*.json (all runs), data/portfolio.json, data/candidates.json
Writes: dashboard/data.js

The scoreboard rolls up every pick from every historical run and refreshes
last prices via yfinance so past picks show performance-since-pick.

Usage: python scripts/publish.py
"""

import json
import datetime as dt
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
HISTORY = DATA / "history"
OUT = ROOT / "dashboard" / "data.js"


def fetch_quotes(tickers: list[str]) -> dict[str, float]:
    if not tickers:
        return {}
    import yfinance as yf
    px = yf.download(sorted(set(tickers)), period="5d", auto_adjust=True, progress=True)["Close"]
    quotes = {}
    if hasattr(px, "columns"):
        for t in px.columns:
            s = px[t].dropna()
            if not s.empty:
                quotes[t] = round(float(s.iloc[-1]), 2)
    else:  # single ticker -> Series
        s = px.dropna()
        if not s.empty:
            quotes[tickers[0]] = round(float(s.iloc[-1]), 2)
    return quotes


def main() -> None:
    runs = sorted(HISTORY.glob("*.json"))
    if not runs:
        raise SystemExit("No history files in data/history/ — nothing to publish")
    latest = json.loads(runs[-1].read_text(encoding="utf-8"))

    portfolio = {"positions": []}
    if (DATA / "portfolio.json").exists():
        portfolio = json.loads((DATA / "portfolio.json").read_text(encoding="utf-8"))

    # Every ticker whose latest price we need
    all_picks = []  # (date, pick) newest run first
    for run_file in reversed(runs):
        run = json.loads(run_file.read_text(encoding="utf-8"))
        for p in run.get("picks", []):
            all_picks.append((run.get("week", run_file.stem), p))
    tickers = [p["ticker"] for _, p in all_picks] + [
        pos["ticker"].upper() for pos in portfolio.get("positions", [])
    ]
    print(f"Refreshing quotes for {len(set(tickers))} tickers...")
    quotes = fetch_quotes(tickers)

    # Holdings verdicts from the latest run
    verdicts = {h["ticker"].upper(): h for h in latest.get("holdingsReview", [])}
    portfolio_rows = []
    for pos in portfolio.get("positions", []):
        t = pos["ticker"].upper()
        v = verdicts.get(t, {})
        portfolio_rows.append({
            "ticker": t,
            "shares": pos["shares"],
            "costBasis": pos["cost_basis"],
            "buyDate": pos.get("buy_date"),
            "lastPrice": quotes.get(t, v.get("lastPrice")),
            "verdict": v.get("verdict"),
            "verdictReason": v.get("verdictReason"),
        })

    scoreboard = [{
        "datePicked": date,
        "ticker": p["ticker"],
        "rating": p.get("rating"),
        "priceAtPick": p.get("price"),
        "lastPrice": quotes.get(p["ticker"], p.get("price")),
    } for date, p in all_picks]

    data = {
        "week": latest.get("week"),
        "generated": latest.get("generated"),
        "pricesAsOf": dt.date.today().isoformat(),
        "picks": latest.get("picks", []),
        "portfolio": portfolio_rows,
        "scoreboard": scoreboard,
    }
    OUT.write_text(
        "/* Regenerated by the weekly agent - do not edit by hand. */\n"
        "window.DASHBOARD_DATA = " + json.dumps(data, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} (week {data['week']}, {len(data['picks'])} picks, "
          f"{len(portfolio_rows)} holdings, {len(scoreboard)} scoreboard rows)")


if __name__ == "__main__":
    main()
