// Real data for the ALDI TM Planning Refinement demo
// Rule data from Rules_BD27_20.07.json and Rules_BD09_V1.json
// FO data from synthetic20_tm_before.csv
// Package data from rule_packages.json

import type {
  AuthState, RuleCandidate, RuleProfile, TmProfileSet,
  FreightOrder, ResourceSummary, RuleDescriptor, RecPackage,
  ChangeSummaryKpi, ValidationCheck,
} from './types';

// ─── Mock users ───────────────────────────────────────────────────────────────
export const MOCK_USERS: AuthState[] = [
  { loggedIn: true, name: 'M. Schmidt',  initials: 'MS', colorScheme: 'Accent6', role: 'planner' },
  { loggedIn: true, name: 'H. Fischer',  initials: 'HF', colorScheme: 'Accent8', role: 'admin'   },
];

// ─── Session constant ─────────────────────────────────────────────────────────
export const SESSION_ID = 'SAP TM-Session-4821';
export const TODAY = '2026-07-20';

// ─── TM Profile Sets (read-only, from SAP TM API) ────────────────────────────
export const MOCK_TM_PROFILE_SETS: TmProfileSet[] = [
  {
    id: 'PS001',
    name: 'Standard Outbound Planning',
    freightUnitSelectionProfile: 'FU_SEL_STD_OUTBOUND',
    freightOrderSelectionProfile: 'FO_SEL_STD_OUTBOUND',
  },
  {
    id: 'PS002',
    name: 'Night Shift Planning',
    freightUnitSelectionProfile: 'FU_SEL_NIGHT_SHIFT',
    freightOrderSelectionProfile: 'FO_SEL_NIGHT_SHIFT',
  },
  {
    id: 'PS003',
    name: 'ALDI Road Freight',
    freightUnitSelectionProfile: 'FU_SEL_ROAD_FREIGHT',
    freightOrderSelectionProfile: 'FO_SEL_ROAD_FREIGHT',
  },
];

// ─── BD27 Rules (from Rules_BD27_20.07.json) ─────────────────────────────────
const BD27_CHECKS: ValidationCheck[] = [
  { id: 'c1', label: 'Rule completeness', status: 'pass', detail: 'All required sections present' },
  { id: 'c2', label: 'Context availability', status: 'pass', detail: 'TM context data available' },
  { id: 'c3', label: 'TM data availability', status: 'pass', detail: 'Required TM data accessible' },
  { id: 'c4', label: 'API / action availability', status: 'pass', detail: 'All required APIs confirmed' },
  { id: 'c5', label: 'Dependency check', status: 'pass', detail: 'No conflicting dependencies' },
  { id: 'c6', label: 'Conflict check', status: 'pass', detail: 'No rule conflicts detected' },
  { id: 'c7', label: 'Sandbox test', status: 'pass', detail: 'Sample payload test passed' },
  { id: 'c8', label: 'Example coverage', status: 'pass', detail: 'Example scenario validated' },
];

const BD09_CHECKS_WARN: ValidationCheck[] = [
  ...BD27_CHECKS.slice(0, 3),
  { id: 'c4', label: 'API / action availability', status: 'warning', detail: 'PTZ delivery time API partially available' },
  ...BD27_CHECKS.slice(4),
];

export const INITIAL_RULES: RuleCandidate[] = [
  // ── BD27 Published Rules ──────────────────────────────────────────────────
  {
    id: 'RC-101',
    name: 'DC-BD27 Low Volume Carrier Allocation',
    group: 'Volume Rules',
    ruleType: 'hard-constraint',
    dc: 'BD27',
    sopDescription: 'For low volume (< 2,500 FUs), carriers receive at least 2 Freight Orders based on fair share allocation. Each carrier receives the same amount of FOs.',
    businessContext: 'Ensures fair distribution of workload across carriers in low-volume planning scenarios. Prevents carrier monopolization and maintains operational equity.',
    exampleScenario: 'Planning day has 1,800 FUs. System detects low volume. All active carriers are assigned minimum 2 FOs each, distributed equally.',
    scopeText: 'DC-BD27 · All active carriers · Volume threshold: < 2,500 FUs',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-001'],
    publishedAt: '2026-01-10',
  },
  {
    id: 'RC-102',
    name: 'DC-BD27 High Volume Carrier Distribution Gate',
    group: 'Volume Rules',
    ruleType: 'hard-constraint',
    dc: 'BD27',
    sopDescription: 'For high volume (> 2,500 FUs), carriers receive FOs according to a strict priority order: ALDI own fleet first, then Paulet, Lenz, Wille, Scholz.',
    businessContext: 'Cost optimization strategy — ALDI own fleet has lowest variable cost; external carriers fill remaining capacity in contracted priority order.',
    exampleScenario: 'Planning day has 3,200 FUs. ALDI own fleet receives maximum capacity allocation. Remaining FOs distributed to Paulet, then Lenz, then Wille, then Scholz.',
    scopeText: 'DC-BD27 · High volume: > 2,500 FUs · Priority: ALDI → Paulet → Lenz → Wille → Scholz',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-001'],
    publishedAt: '2026-01-10',
  },
  {
    id: 'RC-103',
    name: 'DC-BD27 One-Stop Night Store Restriction',
    group: 'Store Rules',
    ruleType: 'hard-constraint',
    dc: 'BD27',
    sopDescription: 'Listed stores can only receive a maximum of one delivery visit per night shift. Stores: ST-B203, ST-B206, ST-B222, ST-B226, ST-B245, ST-B247, ST-B251, ST-B263, ST-B264.',
    businessContext: 'Store-level operational constraint. Night shift deliveries at these locations are limited by unloading dock capacity and staff availability.',
    exampleScenario: 'Night shift planning for ST-B203: if a first FO already services ST-B203, any subsequent FO containing ST-B203 is flagged for reassignment.',
    scopeText: 'DC-BD27 · Night shift only · Stores: ST-B203, ST-B206, ST-B222, ST-B226, ST-B245, ST-B247, ST-B251, ST-B263, ST-B264',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-001'],
    publishedAt: '2026-01-10',
  },
  {
    id: 'RC-104',
    name: 'DC-BD27 Solo 21P Store Assignment',
    group: 'Vehicle Rules',
    ruleType: 'hard-constraint',
    dc: 'BD27',
    sopDescription: 'Stores ST-B206, ST-B210, and ST-B245 require solo 21P resources exclusively. These stores cannot be bundled with other stops or assigned to larger vehicles.',
    businessContext: 'Physical access constraint — loading docks at these stores only accommodate 21P vehicles. Larger vehicles cannot maneuver safely.',
    exampleScenario: 'FO containing ST-B206 is assigned to a 33P resource. Rule fires: reassign to available 21P solo resource.',
    scopeText: 'DC-BD27 · Stores: ST-B206, ST-B210, ST-B245 · Resource type: 21P only · No multi-stop bundling',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-001'],
    publishedAt: '2026-01-10',
  },
  {
    id: 'RC-105',
    name: 'DC-BD27 Solo 27P Store Assignment',
    group: 'Vehicle Rules',
    ruleType: 'hard-constraint',
    dc: 'BD27',
    sopDescription: 'Stores ST-B203, ST-B239, ST-B261, ST-B264, ST-B266, ST-B267, ST-B276 require solo 27P resources. Cannot be combined with other stops.',
    businessContext: 'Dock access and weight distribution constraint for stores with narrow or restricted loading zones.',
    exampleScenario: 'FO with ST-B239 bundled with ST-B241. Rule fires: split FO, assign ST-B239 to solo 27P resource.',
    scopeText: 'DC-BD27 · Stores: ST-B203, ST-B239, ST-B261, ST-B264, ST-B266, ST-B267, ST-B276 · Resource type: 27P solo only',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-001'],
    publishedAt: '2026-01-10',
  },
  {
    id: 'RC-106',
    name: 'DC-BD27 CHL Freezer Combined Transport Restriction',
    group: 'Resource Rules',
    ruleType: 'hard-constraint',
    dc: 'BD27',
    sopDescription: 'Only specific resources approved for combined CHL + Freezer transport. If an FO contains both CHL and Freezer FUs, the resource must be on the approved allowlist.',
    businessContext: 'Temperature chain compliance — not all vehicles are equipped with dual-zone temperature control. Unauthorized combinations risk product quality.',
    exampleScenario: 'FO contains CHL FUs (0002) and Freezer FUs (0003) assigned to standard resource. Rule fires: reassign to CHL+FRZ certified resource.',
    scopeText: 'DC-BD27 · Transportation groups: CHL (0002) + Freezer (0003) combined · Approved resource allowlist applies',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-001'],
    publishedAt: '2026-01-10',
  },
  {
    id: 'RC-107',
    name: 'DC-BD27 Sunday / Holiday Evening Delivery Ban',
    group: 'Time Rules',
    ruleType: 'hard-constraint',
    dc: 'BD27',
    sopDescription: 'Stores ST-B247, ST-B249, ST-B256, ST-B263 must not receive evening deliveries on Sundays or public holidays.',
    businessContext: 'Legal and contractual restriction. Local ordinances and store operational agreements prohibit evening deliveries to these locations on rest days.',
    exampleScenario: 'Planning run for Sunday evening. FO includes ST-B247. Rule fires: block planning, require replanning to Monday morning.',
    scopeText: 'DC-BD27 · Stores: ST-B247, ST-B249, ST-B256, ST-B263 · Day types: SUNDAY, HOLIDAY · Time window: EVENING',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-001'],
    publishedAt: '2026-01-10',
  },
  {
    id: 'RC-108',
    name: 'DC-BD27 Routing Restriction ST-B202 to ST-B218',
    group: 'Store Rules',
    ruleType: 'hard-constraint',
    dc: 'BD27',
    sopDescription: 'The stop sequence ST-B202 → ST-B218 is not permitted. When these stores appear on the same FO, ST-B218 must not follow ST-B202 in the route.',
    businessContext: 'Infrastructure constraint — the road connection between these stores is unsuitable for delivery vehicles (low bridge, weight restriction).',
    exampleScenario: 'FO with stops: DC → ST-B202 → ST-B218 → ST-B225. Rule fires: re-sequence to DC → ST-B218 → ST-B202 → ST-B225.',
    scopeText: 'DC-BD27 · Forbidden sequence: ST-B202 → ST-B218',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-001'],
    publishedAt: '2026-01-10',
  },
  {
    id: 'RC-109',
    name: 'DC-BD27 Maximum Resource Overplanning',
    group: 'Resource Rules',
    ruleType: 'preference',
    dc: 'BD27',
    sopDescription: 'Maximum overplanning allowed is +1 pallet per resource. Resources should not be planned beyond capacity + 1 pallet buffer.',
    businessContext: 'Operational tolerance rule. A small overplan buffer is acceptable to avoid last-minute repacking, but excessive overplanning creates loading issues.',
    exampleScenario: 'Resource capacity is 33 PAL. FO assignment results in 34.5 PAL. Rule fires: redistribute 1.5 PAL excess to another resource.',
    scopeText: 'DC-BD27 · All resources · Maximum buffer: +1 PAL over nominal capacity',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-001'],
    publishedAt: '2026-01-10',
  },
  // ── BD09 Published Rules ──────────────────────────────────────────────────
  {
    id: 'RC-201',
    name: 'DC-BD09 City Store ST-B103 Assignment',
    group: 'Store Rules',
    ruleType: 'hard-constraint',
    dc: 'BD09',
    sopDescription: 'ST-B103 is a city store requiring special forklift-equipped vehicle. Must use ALDI own fleet, morning cockpit only (06:00 shift).',
    businessContext: 'City center store with restricted access. Only forklift-equipped own fleet vehicles can service this location. Daytime parking restrictions apply.',
    exampleScenario: 'FO contains ST-B103 assigned to Paulet carrier. Rule fires: reassign to ALDI own fleet, morning cockpit slot.',
    scopeText: 'DC-BD09 · Store: ST-B103 · Vehicle: ALDI own fleet only · Shift: Morning (06:00) only',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-002'],
    publishedAt: '2026-01-12',
  },
  {
    id: 'RC-202',
    name: 'DC-BD09 PTZ Delivery Time Window',
    group: 'Time Rules',
    ruleType: 'hard-constraint',
    dc: 'BD09',
    sopDescription: 'PTZ (Pick-to-Zero) deliveries must start from 18:00. Exception: ST-B145 has an earlier start window of 17:00.',
    businessContext: 'Store operational requirement. PTZ deliveries require store staff to be present for shelf restocking. Deliveries before the window cannot be processed.',
    exampleScenario: 'PTZ FO (freight type ZF16) planned for 16:30 delivery to ST-B112. Rule fires: delay to 18:00 slot or reassign to later resource.',
    scopeText: 'DC-BD09 · FU types: ZF16, ZF18 (PTZ) · Delivery window: 18:00 start · Exception: ST-B145 → 17:00',
    stage: 'published',
    validationChecks: BD09_CHECKS_WARN,
    assignedProfileIds: ['RP-002'],
    publishedAt: '2026-01-12',
  },
  {
    id: 'RC-203',
    name: 'DC-BD09 Sunday / Holiday Delivery Ban',
    group: 'Time Rules',
    ruleType: 'hard-constraint',
    dc: 'BD09',
    sopDescription: 'Twelve stores must not receive any delivery on Sundays or public holidays: ST-B103, ST-B106, ST-B114, ST-B125, ST-B131, ST-B133, ST-B142, ST-B145, ST-B151, ST-B155, ST-B170, ST-B175.',
    businessContext: 'Regulatory compliance. Sunday trading laws and store agreements prohibit deliveries to these locations on rest days.',
    exampleScenario: 'Planning run for Sunday. FOs contain ST-B103 and ST-B131. Rule fires: block both, require rescheduling to Monday.',
    scopeText: 'DC-BD09 · 12 stores · Day types: SUNDAY, HOLIDAY · Full day ban',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-002'],
    publishedAt: '2026-01-12',
  },
  {
    id: 'RC-204',
    name: 'DC-BD09 After 14:00 Delivery Stores',
    group: 'Time Rules',
    ruleType: 'hard-constraint',
    dc: 'BD09',
    sopDescription: 'Stores ST-B105, ST-B108, ST-B117, ST-B121, ST-B123, ST-B135, ST-B136, ST-B144, ST-B145 must be planned for delivery after 14:00.',
    businessContext: 'Store operational constraint. Morning shifts at these locations are fully occupied with customer service. Delivery windows open in the afternoon.',
    exampleScenario: 'FO with ST-B117 planned for 11:00 delivery. Rule fires: reschedule to 14:30 or later slot.',
    scopeText: 'DC-BD09 · 9 stores · Delivery time: after 14:00',
    stage: 'published',
    validationChecks: BD27_CHECKS,
    assignedProfileIds: ['RP-002'],
    publishedAt: '2026-01-12',
  },
  // ── Draft rules (for admin demo) ──────────────────────────────────────────
  {
    id: 'RC-301',
    name: 'DC-BD27 MilkRun CHL Volume Threshold',
    group: 'Vehicle Rules',
    ruleType: 'preference',
    dc: 'BD27',
    sopDescription: 'MilkRun routing is only used when CHL non-PTZ volume exceeds 300 pallets per day.',
    businessContext: 'Cost-efficiency rule. MilkRun routes have a fixed overhead cost that is only justified at sufficient volume.',
    exampleScenario: 'CHL non-PTZ volume for the day is 280 PAL. MilkRun is not triggered. Volume reaches 320 PAL the next day: MilkRun activated.',
    scopeText: 'DC-BD27 · CHL non-PTZ FUs · Volume threshold: > 300 PAL',
    stage: 'draft',
    validationChecks: [],
    assignedProfileIds: [],
  },
  {
    id: 'RC-302',
    name: 'DC-BD09 Paulet Carrier Three FO Requirement',
    group: 'Volume Rules',
    ruleType: 'hard-constraint',
    dc: 'BD09',
    sopDescription: 'The Paulet carrier must always receive exactly 3 FOs per planning day at DC-BD09.',
    businessContext: 'Contractual SLA with Paulet. Minimum guaranteed volume in the carrier agreement requires exactly 3 FOs per day.',
    exampleScenario: 'Planning complete with only 2 FOs assigned to Paulet. Rule fires: reassign a third FO from lower-priority carrier to Paulet.',
    scopeText: 'DC-BD09 · Carrier: Paulet · Required FOs: exactly 3 per day',
    stage: 'submitted',
    validationChecks: [],
    assignedProfileIds: [],
    submittedAt: '2026-07-18',
  },
];

// ─── Rule Profiles ────────────────────────────────────────────────────────────
export const INITIAL_PROFILES: RuleProfile[] = [
  {
    id: 'RP-001',
    name: 'BD27 Standard Daily',
    dc: 'BD27',
    planningContext: 'Standard daily outbound planning',
    effectiveFrom: '2026-01-01',
    effectiveTo: '2026-12-31',
    status: 'active',
    ruleIds: ['RC-101', 'RC-102', 'RC-103', 'RC-104', 'RC-105', 'RC-106', 'RC-107', 'RC-108', 'RC-109'],
    createdAt: '2025-12-15',
    activatedAt: '2026-01-01',
  },
  {
    id: 'RP-002',
    name: 'BD09 Standard Daily',
    dc: 'BD09',
    planningContext: 'Standard daily outbound planning',
    effectiveFrom: '2026-01-01',
    effectiveTo: '2026-12-31',
    status: 'active',
    ruleIds: ['RC-201', 'RC-202', 'RC-203', 'RC-204'],
    createdAt: '2025-12-15',
    activatedAt: '2026-01-01',
  },
  {
    id: 'RP-003',
    name: 'BD27 Q3 2026 Review',
    dc: 'BD27',
    planningContext: 'Q3 review with MilkRun threshold update',
    effectiveFrom: '2026-07-01',
    effectiveTo: '2026-12-31',
    status: 'draft',
    ruleIds: ['RC-101', 'RC-102', 'RC-103', 'RC-104', 'RC-105', 'RC-106', 'RC-107', 'RC-108', 'RC-109', 'RC-301'],
    createdAt: '2026-06-20',
  },
];

// ─── Freight Orders (from synthetic20_tm_before.csv) ─────────────────────────
export const LOADED_FOS: FreightOrder[] = [
  { id: '80000000000', sapId: '80000000000', dc: 'BD20', resource: 'EBE_ALDI_31_DUMMY_33P_FRZ', stops: 3, pallets: 20.92, distanceKm: 235.9, utilizationPct: 84.1, amountEur: 685.07, overCapacity: false, stopList: 'DC-BD20 → ST-BN42 → ST-BN05' },
  { id: '80000000001', sapId: '80000000001', dc: 'BD42', resource: 'EBE_ALDI_02_DAY_37P',        stops: 4, pallets: 24.0,  distanceKm: 125.5, utilizationPct: 90.7, amountEur: 551.04, overCapacity: false, stopList: 'DC-BD42 → ST-BN04 → ST-BN14 → ST-BN06' },
  { id: '80000000002', sapId: '80000000002', dc: 'BD20', resource: 'EBE_ALDI_03_NIGHT_37P',      stops: 2, pallets: 34.35, distanceKm: 230.8, utilizationPct: 72.7, amountEur: 930.19, overCapacity: false, stopList: 'DC-BD20 → ST-BN06' },
  { id: '80000000003', sapId: '80000000003', dc: 'BD20', resource: 'EBE_ALDI_03_NIGHT_37P',      stops: 3, pallets: 15.2,  distanceKm: 178.8, utilizationPct: 86.4, amountEur: 695.04, overCapacity: false, stopList: 'DC-BD20 → ST-BN08 → ST-BN41 → ST-BN38' },
  { id: '80000000004', sapId: '80000000004', dc: 'BD42', resource: 'EBE_ALDI_31_DUMMY_33P_FRZ', stops: 2, pallets: 20.78, distanceKm: 113.1, utilizationPct: 95.0, amountEur: 533.25, overCapacity: false, stopList: 'DC-BD42 → ST-BN15' },
  { id: '80000000005', sapId: '80000000005', dc: 'BD20', resource: 'EBE_ALDI_30_DUMMY_33P_FRZ', stops: 2, pallets: 20.47, distanceKm: 139.9, utilizationPct: 90.1, amountEur: 622.50, overCapacity: false, stopList: 'DC-BD20 → ST-BN27 → ST-BN35' },
  { id: '80000000006', sapId: '80000000006', dc: 'BD42', resource: 'EBE_ALDI_32_DUMMY_33P_FRZ', stops: 3, pallets: 20.38, distanceKm: 172.4, utilizationPct: 83.6, amountEur: 553.60, overCapacity: false, stopList: 'DC-BD42 → ST-BN53 → ST-BN12 → ST-BN38' },
  { id: '80000000007', sapId: '80000000007', dc: 'BD20', resource: 'EBE_ALDI_32_DUMMY_33P_FRZ', stops: 2, pallets: 24.58, distanceKm: 181.3, utilizationPct: 91.1, amountEur: 720.64, overCapacity: false, stopList: 'DC-BD20 → ST-BN07 → ST-BN46' },
  { id: '80000000008', sapId: '80000000008', dc: 'BD20', resource: 'EBE_ALDI_31_DUMMY_33P_FRZ', stops: 3, pallets: 35.16, distanceKm: 142.4, utilizationPct: 98.0, amountEur: 711.84, overCapacity: false, stopList: 'DC-BD20 → ST-BN14 → ST-BN44 → ST-BN28' },
  { id: '80000000009', sapId: '80000000009', dc: 'BD42', resource: 'EBE_ALDI_04_NIGHT_37P',      stops: 2, pallets: 23.66, distanceKm: 115.0, utilizationPct: 75.8, amountEur: 534.39, overCapacity: false, stopList: 'DC-BD42 → ST-BN20 → ST-BN51' },
  { id: '80000000010', sapId: '80000000010', dc: 'BD20', resource: 'EBE_ALDI_04_DAY_37P',        stops: 3, pallets: 30.6,  distanceKm: 140.2, utilizationPct: 93.9, amountEur: 678.13, overCapacity: false, stopList: 'DC-BD20 → ST-BN20 → ST-BN32 → ST-BN47' },
  { id: '80000000011', sapId: '80000000011', dc: 'BD20', resource: 'EBE_ALDI_01_NIGHT_37P',      stops: 1, pallets: 12.98, distanceKm: 143.0, utilizationPct: 96.1, amountEur: 599.72, overCapacity: false, stopList: 'DC-BD20 → ST-BN33' },
  { id: '80000000012', sapId: '80000000012', dc: 'BD42', resource: 'EBE_ALDI_30_DUMMY_33P_FRZ', stops: 1, pallets: 19.22, distanceKm: 205.4, utilizationPct: 73.9, amountEur: 606.01, overCapacity: false, stopList: 'DC-BD42 → ST-BN32' },
  { id: '80000000013', sapId: '80000000013', dc: 'BD20', resource: 'EBE_ALDI_01_DAY_37P',        stops: 3, pallets: 31.71, distanceKm: 140.7, utilizationPct: 103.4, amountEur: 634.47, overCapacity: true,  stopList: 'DC-BD20 → ST-BN37 → ST-BN22 → ST-BN23' },
  { id: '80000000014', sapId: '80000000014', dc: 'BD42', resource: 'EBE_ALDI_04_NIGHT_37P',      stops: 1, pallets: 15.08, distanceKm: 79.5,  utilizationPct: 78.3, amountEur: 379.61, overCapacity: false, stopList: 'DC-BD42 → ST-BN54' },
  { id: '80000000015', sapId: '80000000015', dc: 'BD42', resource: 'EBE_ALDI_31_DUMMY_33P_FRZ', stops: 4, pallets: 20.95, distanceKm: 202.4, utilizationPct: 104.3, amountEur: 648.83, overCapacity: true,  stopList: 'DC-BD42 → ST-BN43 → ST-BN04 → ST-BN45' },
  { id: '80000000016', sapId: '80000000016', dc: 'BD42', resource: 'EBE_ALDI_32_DUMMY_33P_FRZ', stops: 2, pallets: 16.74, distanceKm: 211.4, utilizationPct: 84.1, amountEur: 779.65, overCapacity: false, stopList: 'DC-BD42 → ST-BN46 → ST-BN57' },
  { id: '80000000017', sapId: '80000000017', dc: 'BD20', resource: 'EBE_ALDI_02_NIGHT_37P',      stops: 2, pallets: 15.95, distanceKm: 204.5, utilizationPct: 73.0, amountEur: 746.25, overCapacity: false, stopList: 'DC-BD20 → ST-BN23 → ST-BN40' },
  { id: '80000000018', sapId: '80000000018', dc: 'BD20', resource: 'EBE_ALDI_31_DUMMY_33P_FRZ', stops: 1, pallets: 12.09, distanceKm: 183.9, utilizationPct: 72.6, amountEur: 520.21, overCapacity: false, stopList: 'DC-BD20 → ST-BN50' },
  { id: '80000000019', sapId: '80000000019', dc: 'BD20', resource: 'EBE_ALDI_03_DAY_37P',        stops: 2, pallets: 26.17, distanceKm: 99.7,  utilizationPct: 97.9, amountEur: 480.68, overCapacity: false, stopList: 'DC-BD20 → ST-BN26 → ST-BN06' },
];

// ─── Resource Summary ─────────────────────────────────────────────────────────
export const RESOURCE_SUMMARY: ResourceSummary[] = [
  { resourceId: 'EBE_ALDI_31_DUMMY_33P_FRZ', dc: 'BD20/BD42', tours: 5, totalPallets: 89.94, avgUtilization: 87.6 },
  { resourceId: 'EBE_ALDI_32_DUMMY_33P_FRZ', dc: 'BD20/BD42', tours: 3, totalPallets: 61.70, avgUtilization: 86.3 },
  { resourceId: 'EBE_ALDI_30_DUMMY_33P_FRZ', dc: 'BD20/BD42', tours: 2, totalPallets: 39.69, avgUtilization: 82.0 },
  { resourceId: 'EBE_ALDI_01_DAY_37P',        dc: 'BD20',      tours: 1, totalPallets: 31.71, avgUtilization: 103.4 },
  { resourceId: 'EBE_ALDI_02_DAY_37P',        dc: 'BD42',      tours: 1, totalPallets: 24.0,  avgUtilization: 90.7 },
  { resourceId: 'EBE_ALDI_03_DAY_37P',        dc: 'BD20',      tours: 1, totalPallets: 26.17, avgUtilization: 97.9 },
  { resourceId: 'EBE_ALDI_04_DAY_37P',        dc: 'BD20',      tours: 1, totalPallets: 30.6,  avgUtilization: 93.9 },
  { resourceId: 'EBE_ALDI_01_NIGHT_37P',      dc: 'BD20',      tours: 1, totalPallets: 12.98, avgUtilization: 96.1 },
  { resourceId: 'EBE_ALDI_02_NIGHT_37P',      dc: 'BD20',      tours: 1, totalPallets: 15.95, avgUtilization: 73.0 },
  { resourceId: 'EBE_ALDI_03_NIGHT_37P',      dc: 'BD20',      tours: 2, totalPallets: 49.55, avgUtilization: 79.5 },
  { resourceId: 'EBE_ALDI_04_NIGHT_37P',      dc: 'BD42',      tours: 2, totalPallets: 38.74, avgUtilization: 77.1 },
];

// ─── Session KPIs ─────────────────────────────────────────────────────────────
export const SESSION_KPIS = {
  freightOrders: 20,
  deliveryStops: 41,
  totalPallets: 440.1,
  resources: 11,
  totalDistanceKm: 3246.7,
  avgUtilization: 86.2,
  totalCostEur: 11631.1,
  overCapacity: 2,
};

// ─── Rule Descriptors for Rule Evaluation ────────────────────────────────────
export const EVAL_RULE_DESCRIPTORS: RuleDescriptor[] = [
  {
    id: 'R-001',
    name: 'DC-BD27 Maximum Resource Overplanning',
    group: 'Resource Rules',
    ruleType: 'hard-constraint',
    sopDescription: 'Maximum overplanning allowed is +1 pallet per resource.',
    businessContext: 'Operational tolerance rule. Prevents loading issues at the dock.',
    exampleScenario: 'Resource capacity 33 PAL. FO assignment 34.5 PAL. Redistribute 1.5 PAL excess.',
    scopeText: 'DC-BD27 · All resources · Buffer: +1 PAL max',
    matchedCount: 2,
    evalStatus: 'pending',
  },
  {
    id: 'R-002',
    name: 'DC-BD27 Low Volume Carrier Allocation',
    group: 'Volume Rules',
    ruleType: 'hard-constraint',
    sopDescription: 'For low volume (< 2,500 FUs), carriers get at least 2 FOs via fair share.',
    businessContext: 'Ensures fair carrier distribution in low-volume scenarios.',
    exampleScenario: '1,800 FUs today. All carriers assigned ≥ 2 FOs each.',
    scopeText: 'DC-BD27 · Volume threshold: < 2,500 FUs',
    matchedCount: 1,
    evalStatus: 'pending',
  },
  {
    id: 'R-003',
    name: 'DC-BD27 One-Stop Night Store Restriction',
    group: 'Store Rules',
    ruleType: 'hard-constraint',
    sopDescription: 'One-stop night stores can receive max 1 visit per night shift.',
    businessContext: 'Dock capacity and night staff limitation at these stores.',
    exampleScenario: 'Second FO with ST-B203 during night shift: flagged for reassignment.',
    scopeText: 'DC-BD27 · Night shift · Stores: ST-B203, ST-B206, ST-B222 +6 more',
    matchedCount: 0,
    evalStatus: 'pending',
  },
  {
    id: 'R-004',
    name: 'DC-BD27 Sunday/Holiday Evening Delivery Ban',
    group: 'Time Rules',
    ruleType: 'hard-constraint',
    sopDescription: 'ST-B247, ST-B249, ST-B256, ST-B263 cannot receive evening deliveries on Sundays or holidays.',
    businessContext: 'Legal and contractual restriction on rest day deliveries.',
    exampleScenario: 'Sunday evening plan includes ST-B247. Block and reschedule to Monday.',
    scopeText: 'DC-BD27 · 4 stores · Day: SUNDAY/HOLIDAY · Window: EVENING',
    matchedCount: 0,
    evalStatus: 'pending',
  },
  {
    id: 'R-005',
    name: 'DC-BD27 Routing Restriction ST-B202 → ST-B218',
    group: 'Store Rules',
    ruleType: 'hard-constraint',
    sopDescription: 'Route sequence ST-B202 → ST-B218 is not permitted.',
    businessContext: 'Infrastructure constraint — unsuitable road between these stores.',
    exampleScenario: 'FO stops: DC → ST-B202 → ST-B218. Re-sequence to reverse order.',
    scopeText: 'DC-BD27 · Forbidden sequence: ST-B202 → ST-B218',
    matchedCount: 0,
    evalStatus: 'pending',
  },
];

// ─── Recommendation Packages (from rule_packages.json) ───────────────────────
export const INITIAL_PACKAGES: RecPackage[] = [
  {
    id: 'PKG-001',
    title: 'Resolve over-capacity FO-80000000013 (103.4% → 91.2%)',
    ruleId: 'R-001',
    ruleName: 'DC-BD27 Maximum Resource Overplanning',
    state: 'ready',
    whyText: 'FO-80000000013 (EBE_ALDI_01_DAY_37P, BD20) loaded to 103.4%, exceeding the +1 PAL tolerance. Redistributing 3.71 PAL to FO-80000000010 on the same corridor brings utilization to 91.2%, within acceptable range.',
    affectedObjects: [
      { kind: 'FO', id: 'FO-80000000013', description: '103.4% → 91.2% utilization after redistribution' },
      { kind: 'FO', id: 'FO-80000000010', description: '93.9% → 100.6% utilization after receiving excess load' },
      { kind: 'FU', id: 'FU-2107', description: '3.71 PAL reassigned from FO-80000000013 to FO-80000000010' },
    ],
    validationChecks: [
      { passed: true,  label: 'Target FO has sufficient capacity headroom' },
      { passed: true,  label: 'Same distribution corridor (BD20 — South)' },
      { passed: true,  label: 'Delivery window compatibility confirmed' },
      { passed: true,  label: 'Resource type compatible (37P → 37P)' },
    ],
    tmActions: [
      { description: 'Reassign FU-2107 (3.71 PAL) from FO-80000000013 to FO-80000000010' },
      { description: 'Recompute route distance for FO-80000000013' },
      { description: 'Recompute route distance for FO-80000000010' },
    ],
    kpiComparison: [
      { label: 'FO-80000000013 Utilization', before: '103.4%', after: '91.2%' },
      { label: 'FO-80000000010 Utilization', before: '93.9%', after: '100.6%' },
      { label: 'FO-80000000013 Pallets',     before: '31.71 PAL', after: '28.0 PAL' },
      { label: 'FO-80000000010 Pallets',     before: '30.6 PAL',  after: '34.31 PAL' },
      { label: 'Distance saved',             before: '—',         after: '−8.2 km' },
    ],
  },
  {
    id: 'PKG-002',
    title: 'Resolve over-capacity FO-80000000015 (104.3% → 89.7%)',
    ruleId: 'R-001',
    ruleName: 'DC-BD27 Maximum Resource Overplanning',
    state: 'ready',
    whyText: 'FO-80000000015 (EBE_ALDI_31_DUMMY_33P_FRZ, BD42) loaded to 104.3%, 4.3 points over capacity. Redistributing excess 0.89 PAL to FO-80000000006 on the same freezer corridor.',
    affectedObjects: [
      { kind: 'FO', id: 'FO-80000000015', description: '104.3% → 89.7% utilization after redistribution' },
      { kind: 'FO', id: 'FO-80000000006', description: '83.6% → 87.4% utilization after receiving FU' },
      { kind: 'FU', id: 'FU-2418', description: '0.89 PAL reassigned to FO-80000000006' },
    ],
    validationChecks: [
      { passed: true,  label: 'Target FO has sufficient capacity headroom' },
      { passed: true,  label: 'Both FOs are DUMMY_33P_FRZ compatible' },
      { passed: true,  label: 'BD42 corridor — same distribution zone' },
      { passed: false, label: 'Existing stop sequence revalidation required' },
    ],
    tmActions: [
      { description: 'Reassign FU-2418 (0.89 PAL) from FO-80000000015 to FO-80000000006' },
      { description: 'Append stop ST-BN43 to FO-80000000006' },
      { description: 'Recompute route distance for both FOs' },
    ],
    kpiComparison: [
      { label: 'FO-80000000015 Utilization', before: '104.3%', after: '89.7%' },
      { label: 'FO-80000000006 Utilization', before: '83.6%', after: '87.4%' },
      { label: 'Distance change',            before: '202.4 km', after: '195.2 km' },
    ],
  },
  {
    id: 'PKG-003',
    title: 'Fair share: assign 2nd FO to carrier Lenz (Low volume)',
    ruleId: 'R-002',
    ruleName: 'DC-BD27 Low Volume Carrier Allocation',
    state: 'ready',
    whyText: 'Today\'s volume is 1,920 FUs (low volume threshold < 2,500). Carrier "Lenz" currently has only 1 FO assigned, while other carriers have 2. Fair share requires minimum 2 FOs per active carrier.',
    affectedObjects: [
      { kind: 'FO', id: 'FO-80000000009', description: 'Reassigned from overflow pool to Lenz carrier (EBE_ALDI_04_NIGHT_37P)' },
    ],
    validationChecks: [
      { passed: true, label: 'Volume below 2,500 FU threshold (1,920 FUs)' },
      { passed: true, label: 'Carrier Lenz has active contract and available resource' },
      { passed: true, label: 'FO within Lenz carrier operational zone' },
    ],
    tmActions: [
      { description: 'Reassign FO-80000000009 to Lenz carrier resource' },
      { description: 'Update carrier assignment in TM planning cockpit' },
    ],
    kpiComparison: [
      { label: 'Lenz carrier FO count', before: '1', after: '2' },
      { label: 'Fair share variance',   before: '−1 vs avg', after: '0 (aligned)' },
    ],
  },
  {
    id: 'PKG-004',
    title: 'No admissible solution — FO-80000000008 rebalancing',
    ruleId: 'R-001',
    ruleName: 'DC-BD27 Maximum Resource Overplanning',
    state: 'nosol',
    whyText: 'Rule R-001 fired because FO-80000000008 is at 98.0% utilization with 35.16 PAL. No target FO satisfies both corridor-compatibility and remaining capacity requirements. All same-corridor FOs are above 90% utilization.',
    affectedObjects: [
      { kind: 'FO', id: 'FO-80000000008', description: '98.0% utilization — near limit but no viable redistribution target' },
    ],
    validationChecks: [
      { passed: false, label: 'No target FO with ≥ 3 PAL headroom on same corridor' },
      { passed: false, label: 'Cross-corridor transfer not permitted (FRZ constraint)' },
    ],
    tmActions: [],
    kpiComparison: [],
  },
  {
    id: 'PKG-005',
    title: 'Re-sequence stops on FO-80000000001 (avoid ST-BN04 delay)',
    ruleId: 'R-003',
    ruleName: 'DC-BD27 One-Stop Night Store Restriction',
    state: 'pending',
    whyText: 'Current stop sequence for FO-80000000001 places ST-BN04 at position 1, resulting in a 14-minute estimated arrival delay. Re-sequencing ST-BN14 first reduces total route by 12.3 km and ensures on-time arrival.',
    affectedObjects: [
      { kind: 'FO', id: 'FO-80000000001', description: 'Stop re-sequenced: ST-BN04 → ST-BN14 → ST-BN06 reordered to ST-BN14 → ST-BN04 → ST-BN06' },
      { kind: 'Stop', id: 'ST-BN04', description: 'Position changed from stop 1 to stop 2' },
      { kind: 'Stop', id: 'ST-BN14', description: 'Position changed from stop 2 to stop 1' },
    ],
    validationChecks: [
      { passed: true, label: 'All delivery windows satisfied after re-sequence' },
      { passed: true, label: 'No one-stop night store restriction violated' },
      { passed: true, label: 'Total distance reduced by 12.3 km' },
    ],
    tmActions: [
      { description: 'Re-sequence stops on FO-80000000001: ST-BN14 first, then ST-BN04' },
      { description: 'Recompute ETA for all stops on FO-80000000001' },
      { description: 'Update route distance in TM session' },
    ],
    kpiComparison: [
      { label: 'FO-80000000001 Distance', before: '125.5 km', after: '113.2 km' },
      { label: 'ST-BN04 ETA',             before: 'Delayed +14 min', after: 'On time' },
    ],
  },
  {
    id: 'PKG-006',
    title: 'Apply Sunday delivery ban for ST-BN23 (Holiday planning)',
    ruleId: 'R-004',
    ruleName: 'DC-BD27 Sunday/Holiday Evening Delivery Ban',
    state: 'pending',
    whyText: 'Tomorrow is a public holiday. Store ST-BN23 appears in FO-80000000017 with an evening delivery window. The Sunday/Holiday Evening Ban requires this delivery to be blocked and rescheduled.',
    affectedObjects: [
      { kind: 'FO', id: 'FO-80000000017', description: 'Delivery to ST-BN23 blocked — holiday evening ban applies' },
      { kind: 'Stop', id: 'ST-BN23', description: 'Removed from FO-80000000017, requires manual rescheduling to next day' },
    ],
    validationChecks: [
      { passed: true, label: 'Holiday day type confirmed in planning calendar' },
      { passed: true, label: 'Store ST-BN23 is on the restricted stores list' },
      { passed: false, label: 'Rescheduled delivery slot must be confirmed manually' },
    ],
    tmActions: [
      { description: 'Remove stop ST-BN23 from FO-80000000017' },
      { description: 'Flag FU for manual rescheduling to next available slot' },
    ],
    kpiComparison: [
      { label: 'Unplanned FUs', before: '0', after: '1 (requires manual scheduling)' },
      { label: 'FO-80000000017 Stops', before: '2', after: '1' },
    ],
  },
];

// ─── Change Summary KPIs ──────────────────────────────────────────────────────
export const CHANGE_SUMMARY_KPIS: ChangeSummaryKpi[] = [
  { label: 'Pallets total',          before: '440.1',    after: '440.1',   unit: 'PAL',  improved: false },
  { label: 'Number of FOs',          before: '20',       after: '20',      unit: 'FOs',  improved: false },
  { label: 'Number of stops',        before: '41',       after: '40',      unit: 'stops', improved: true },
  { label: 'Unplanned FUs',          before: '0',        after: '1',       unit: 'FUs',  improved: false },
  { label: 'Utilization (avg)',       before: '86.2%',    after: '88.1%',   improved: true },
  { label: 'Total distance / day',   before: '3,246.7',  after: '3,226.4', unit: 'km',   improved: true },
  { label: 'Pallets per FO (avg)',    before: '22.0',     after: '22.0',    unit: 'PAL',  improved: false },
  { label: 'Distance per FO (avg)',   before: '162.3',    after: '161.3',   unit: 'km',   improved: true },
  { label: 'Tour plan cost',         before: '11,631',   after: '11,514',  unit: 'EUR',  improved: true },
];
