// Bayer Collections Worklist — mock data
// Derived from fde-template/app/bayer-worklist/mock/data.json

export interface BayerCustomer {
  id: string;
  customerNumber: string;
  customerName: string;
  customerContact: string;
  contactEmail: string;
  assignedTo: string;
  priority: 1 | 2 | 3;
  amountOutstanding: number;
  amountOutstandingEur: number;
  currency: string;
  dsoPerCustomer: number;
  maxArrearsDays: number;
  maxPredDelayed: number;
  lastCommDate: string;
  creditLimit: number;
  creditExposure: number;
  creditUtilizationRate: number;
  blockedOrdersCount: number;
  blockedOrdersAmount: number;
  overdueCount: number;
  due7DaysCount: number;
  disputesCount: number;
  overdueAmount: number;
  due7DaysAmount: number;
  disputesAmount: number;
  maxDaysOverdue: number;
  hasAiInsights: boolean;
  accountSummary: string;
  recommendedAction: string;
  hitlPending: boolean;
  hitlSubject?: string;
}

export interface BayerCommunication {
  id: string;
  customerId: string;
  direction: 'outbound' | 'inbound';
  subject: string;
  body: string;
  sentDate: string;
  fromEmail: string;
  toEmail: string;
  sentiment: 'neutral' | 'positive' | 'negative';
  summary: string;
}

export interface BayerInvoice {
  id: string;
  customerId: string;
  documentNumber: string;
  documentTypeText: string;
  amount: number;
  currency: string;
  dueDate: string;
  isOverdue: boolean;
  daysOverdue: number;
}

export interface BayerActivity {
  id: string;
  customerId: string;
  timestamp: string;
  description: string;
  performedBy: string;
}

export const CUSTOMERS: BayerCustomer[] = [
  {
    id: '06f6d03a',
    customerNumber: '89068',
    customerName: 'Northern Ohio Medical Spc LLC',
    customerContact: 'Dr. James Patterson',
    contactEmail: 'james.patterson@nf3q.onmicrosoft.com',
    assignedTo: 'Jordan Lee',
    priority: 1,
    amountOutstanding: 87988.04,
    amountOutstandingEur: 76219.72,
    currency: 'USD',
    dsoPerCustomer: 29,
    maxArrearsDays: 113,
    maxPredDelayed: 112,
    lastCommDate: '12/05/2025',
    creditLimit: 115000,
    creditExposure: 87988.04,
    creditUtilizationRate: 76.51,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 5,
    due7DaysCount: 2,
    disputesCount: 1,
    overdueAmount: 59201.24,
    due7DaysAmount: 28786.80,
    disputesAmount: 9595.60,
    maxDaysOverdue: 113,
    hasAiInsights: true,
    accountSummary: 'Northern Ohio Medical has 5 overdue invoices with the oldest at 113 days past due. A dispute case of $9,595.60 (deductions/claims) is open and may be contributing to the payment delay. Customer proposed a payment plan ($45K by Nov 29, remainder by Dec 15) but the first payment was not received. Immediate follow-up required.',
    recommendedAction: 'Email Customer',
    hitlPending: true,
    hitlSubject: 'Follow-up: Missed Payment — Northern Ohio Medical $87,988.04',
  },
  {
    id: '12607aaa',
    customerNumber: '12607',
    customerName: 'INSTITUT GUSTAVE ROUSSY',
    customerContact: 'Pierre Lambert',
    contactEmail: 'p.lambert@igr.fr',
    assignedTo: 'Sarah Kim',
    priority: 1,
    amountOutstanding: 82011,
    amountOutstandingEur: 82011,
    currency: 'USD',
    dsoPerCustomer: 24,
    maxArrearsDays: 72,
    maxPredDelayed: 38,
    lastCommDate: '12/05/2025',
    creditLimit: 300000,
    creditExposure: 130000,
    creditUtilizationRate: 43.3,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 3,
    due7DaysCount: 0,
    disputesCount: 1,
    overdueAmount: 82011,
    due7DaysAmount: 0,
    disputesAmount: 8500,
    maxDaysOverdue: 72,
    hasAiInsights: true,
    accountSummary: 'IGR has a dispute case open for $8.5K which may be impacting their payment. DSO is low (24 days) — overall a reliable payer. Resolving the dispute is the priority action.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: '12614fff',
    customerNumber: '12614',
    customerName: 'Institut Bergonié',
    customerContact: 'Marie Dupont',
    contactEmail: 'm.dupont@bergonie.fr',
    assignedTo: 'Sarah Kim',
    priority: 1,
    amountOutstanding: 96671,
    amountOutstandingEur: 82306,
    currency: 'USD',
    dsoPerCustomer: 2,
    maxArrearsDays: 2,
    maxPredDelayed: 75,
    lastCommDate: '12/11/2025',
    creditLimit: 200000,
    creditExposure: 110000,
    creditUtilizationRate: 55.0,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 6,
    due7DaysCount: 1,
    disputesCount: 0,
    overdueAmount: 96671,
    due7DaysAmount: 12000,
    disputesAmount: 0,
    maxDaysOverdue: 133,
    hasAiInsights: true,
    accountSummary: 'Institut Bergonié shows a pattern of slow payment — average 99 DSO for the past 3 quarters. No disputes on record. Recommend structured payment plan discussion.',
    recommendedAction: 'Email Customer',
    hitlPending: true,
    hitlSubject: 'Payment Reminder — Institut Bergonié $96,671',
  },
  {
    id: '170758cc',
    customerNumber: '170758',
    customerName: 'Norton Healthcare',
    customerContact: 'James Norton',
    contactEmail: 'j.norton@nortonhealthcare.com',
    assignedTo: 'Jordan Lee',
    priority: 1,
    amountOutstanding: 82011,
    amountOutstandingEur: 82011,
    currency: 'USD',
    dsoPerCustomer: 24,
    maxArrearsDays: 72,
    maxPredDelayed: 38,
    lastCommDate: '12/05/2025',
    creditLimit: 500000,
    creditExposure: 280000,
    creditUtilizationRate: 56.0,
    blockedOrdersCount: 2,
    blockedOrdersAmount: 25000,
    overdueCount: 4,
    due7DaysCount: 3,
    disputesCount: 0,
    overdueAmount: 82011,
    due7DaysAmount: 67000,
    disputesAmount: 0,
    maxDaysOverdue: 86,
    hasAiInsights: true,
    accountSummary: 'Norton Healthcare has $25K in blocked orders. 3 invoices due within 7 days — potential for escalation if not collected. Previous reminder on file had no response.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: '121437bb',
    customerNumber: '121437',
    customerName: 'Trustees of the University of PA',
    customerContact: 'Michael Chen',
    contactEmail: 'mchen@upenn.edu',
    assignedTo: 'Jordan Lee',
    priority: 1,
    amountOutstanding: 93727,
    amountOutstandingEur: 93727,
    currency: 'USD',
    dsoPerCustomer: 99,
    maxArrearsDays: 133,
    maxPredDelayed: 69,
    lastCommDate: '12/06/2025',
    creditLimit: 800000,
    creditExposure: 520000,
    creditUtilizationRate: 65.0,
    blockedOrdersCount: 1,
    blockedOrdersAmount: 8000,
    overdueCount: 5,
    due7DaysCount: 0,
    disputesCount: 2,
    overdueAmount: 93727,
    due7DaysAmount: 0,
    disputesAmount: 22000,
    maxDaysOverdue: 114,
    hasAiInsights: true,
    accountSummary: 'UPenn has 5 overdue invoices — oldest at 114 days. Two active dispute cases totaling $22K may be blocking payment. AI recommends escalating dispute resolution before pursuing direct collections.',
    recommendedAction: 'Call Customer',
    hitlPending: true,
    hitlSubject: 'Call Customer — University of PA Outstanding Balance',
  },
  {
    id: '20152eee',
    customerNumber: '20152',
    customerName: 'SELARL JEAN DE BERRY',
    customerContact: 'Jean Berry',
    contactEmail: 'j.berry@jeandeberry.fr',
    assignedTo: 'Sarah Kim',
    priority: 1,
    amountOutstanding: 217810,
    amountOutstandingEur: 185445,
    currency: 'USD',
    dsoPerCustomer: 61,
    maxArrearsDays: 86,
    maxPredDelayed: 234,
    lastCommDate: '12/04/2025',
    creditLimit: 400000,
    creditExposure: 230000,
    creditUtilizationRate: 57.5,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 4,
    due7DaysCount: 0,
    disputesCount: 0,
    overdueAmount: 217810,
    due7DaysAmount: 0,
    disputesAmount: 0,
    maxDaysOverdue: 86,
    hasAiInsights: false,
    accountSummary: 'SELARL Jean de Berry has 4 overdue invoices. No AI insights generated. Manual review recommended.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: '19136ccc',
    customerNumber: '19136',
    customerName: 'Cache Valley Womens Center PLLC',
    customerContact: 'Dr. Lisa Park',
    contactEmail: 'lpark@cachevalley.com',
    assignedTo: 'Jordan Lee',
    priority: 1,
    amountOutstanding: 412085,
    amountOutstandingEur: 3752,
    currency: 'USD',
    dsoPerCustomer: 69,
    maxArrearsDays: 114,
    maxPredDelayed: 49,
    lastCommDate: '12/08/2025',
    creditLimit: 150000,
    creditExposure: 110000,
    creditUtilizationRate: 73.3,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 1,
    due7DaysCount: 0,
    disputesCount: 0,
    overdueAmount: 412085,
    due7DaysAmount: 0,
    disputesAmount: 0,
    maxDaysOverdue: 2,
    hasAiInsights: false,
    accountSummary: 'Cache Valley Womens Center — high overdue amount. Likely a recent invoicing issue.',
    recommendedAction: 'Review and Approve',
    hitlPending: true,
    hitlSubject: 'Review and Approve — Cache Valley Collections Strategy',
  },
  {
    id: '19464fff',
    customerNumber: '19464',
    customerName: 'CHU DE NICE  HOPITAL PASTEUR',
    customerContact: 'Dr. Nicole Pasteur',
    contactEmail: 'n.pasteur@chunice.fr',
    assignedTo: 'Sarah Kim',
    priority: 1,
    amountOutstanding: 77612,
    amountOutstandingEur: 77612,
    currency: 'USD',
    dsoPerCustomer: 99,
    maxArrearsDays: 680,
    maxPredDelayed: 12,
    lastCommDate: '12/03/2025',
    creditLimit: 200000,
    creditExposure: 100000,
    creditUtilizationRate: 50.0,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 3,
    due7DaysCount: 0,
    disputesCount: 0,
    overdueAmount: 77612,
    due7DaysAmount: 0,
    disputesAmount: 0,
    maxDaysOverdue: 680,
    hasAiInsights: true,
    accountSummary: 'CHU de Nice has an invoice 680 days overdue — exceptional aging. Requires immediate escalation to senior collections.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: 'fe362849',
    customerNumber: '103104',
    customerName: 'DuPage Medical Group Ltd',
    customerContact: 'Dr. Anthony Marin',
    contactEmail: 'an_marin@outlook.com',
    assignedTo: 'Jordan Lee',
    priority: 2,
    amountOutstanding: 1010456,
    amountOutstandingEur: 860306,
    currency: 'USD',
    dsoPerCustomer: 25,
    maxArrearsDays: 49,
    maxPredDelayed: 196,
    lastCommDate: '12/09/2025',
    creditLimit: 1400000,
    creditExposure: 1031530,
    creditUtilizationRate: 73.7,
    blockedOrdersCount: 3,
    blockedOrdersAmount: 15000,
    overdueCount: 8,
    due7DaysCount: 2,
    disputesCount: 1,
    overdueAmount: 1010456,
    due7DaysAmount: 42000,
    disputesAmount: 5000,
    maxDaysOverdue: 49,
    hasAiInsights: true,
    accountSummary: 'DuPage Medical Group has 8 overdue invoices totaling over $1M. DSO is 25 days, below the segment average. Credit utilization at 73.7% — approaching the $1.4M limit. Recommend immediate outreach to the AP contact before credit block is triggered.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: '103104aa',
    customerNumber: '103104',
    customerName: 'SASU HOPITAL PRIVE NANCY LORRAINE',
    customerContact: 'Pierre Nancy',
    contactEmail: 'p.nancy@hpnl.fr',
    assignedTo: 'Sarah Kim',
    priority: 2,
    amountOutstanding: 14667,
    amountOutstandingEur: 14667,
    currency: 'USD',
    dsoPerCustomer: 11,
    maxArrearsDays: 11,
    maxPredDelayed: 78,
    lastCommDate: '12/10/2025',
    creditLimit: 80000,
    creditExposure: 20000,
    creditUtilizationRate: 25.0,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 1,
    due7DaysCount: 0,
    disputesCount: 0,
    overdueAmount: 14667,
    due7DaysAmount: 0,
    disputesAmount: 0,
    maxDaysOverdue: 11,
    hasAiInsights: false,
    accountSummary: 'Minor overdue balance — standard reminder sufficient.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: '12658ggg',
    customerNumber: '12658',
    customerName: 'CENTRE GEORGESFRANCOIS LECLERC',
    customerContact: 'Georges Leclerc',
    contactEmail: 'g.leclerc@centreleclerc.fr',
    assignedTo: 'Jordan Lee',
    priority: 2,
    amountOutstanding: 27337,
    amountOutstandingEur: 27337,
    currency: 'CAD',
    dsoPerCustomer: 31,
    maxArrearsDays: 42,
    maxPredDelayed: 25,
    lastCommDate: '12/07/2025',
    creditLimit: 100000,
    creditExposure: 35000,
    creditUtilizationRate: 35.0,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 2,
    due7DaysCount: 0,
    disputesCount: 0,
    overdueAmount: 27337,
    due7DaysAmount: 0,
    disputesAmount: 0,
    maxDaysOverdue: 42,
    hasAiInsights: false,
    accountSummary: 'Moderate overdue balance. No AI analysis generated.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: '121883dd',
    customerNumber: '121883',
    customerName: 'Siemens Healthcare Limited',
    customerContact: 'Klaus Weber',
    contactEmail: 'k.weber@siemens-healthineers.com',
    assignedTo: 'Sarah Kim',
    priority: 2,
    amountOutstanding: 19173,
    amountOutstandingEur: 11765,
    currency: 'CAD',
    dsoPerCustomer: 21,
    maxArrearsDays: 21,
    maxPredDelayed: 45,
    lastCommDate: '12/10/2025',
    creditLimit: 1000000,
    creditExposure: 340000,
    creditUtilizationRate: 34.0,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 1,
    due7DaysCount: 5,
    disputesCount: 0,
    overdueAmount: 19173,
    due7DaysAmount: 150000,
    disputesAmount: 0,
    maxDaysOverdue: 21,
    hasAiInsights: true,
    accountSummary: 'Siemens Healthcare is a strategic account. Minor overdue balance — likely processing delay. $150K due within 7 days. Standard reminder recommended.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: '12608bbb',
    customerNumber: '12608',
    customerName: 'CLCC OSCAR LAMBRET',
    customerContact: 'Isabelle Martin',
    contactEmail: 'i.martin@clcc-lambret.fr',
    assignedTo: 'Sarah Kim',
    priority: 2,
    amountOutstanding: 11715,
    amountOutstandingEur: 11715,
    currency: 'USD',
    dsoPerCustomer: 9,
    maxArrearsDays: 18,
    maxPredDelayed: 12,
    lastCommDate: '12/09/2025',
    creditLimit: 100000,
    creditExposure: 30000,
    creditUtilizationRate: 30.0,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 2,
    due7DaysCount: 0,
    disputesCount: 0,
    overdueAmount: 11715,
    due7DaysAmount: 0,
    disputesAmount: 0,
    maxDaysOverdue: 18,
    hasAiInsights: false,
    accountSummary: 'Low overdue balance, good credit standing. Minor delay likely administrative.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: '171307hhh',
    customerNumber: '171307',
    customerName: 'IU HEALTH',
    customerContact: 'Indiana Health',
    contactEmail: 'billing@iuhealth.org',
    assignedTo: 'Jordan Lee',
    priority: 3,
    amountOutstanding: 291979,
    amountOutstandingEur: 291979,
    currency: 'CAD',
    dsoPerCustomer: 0,
    maxArrearsDays: -62,
    maxPredDelayed: 15,
    lastCommDate: '12/11/2025',
    creditLimit: 600000,
    creditExposure: 350000,
    creditUtilizationRate: 58.3,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 0,
    due7DaysCount: 4,
    disputesCount: 0,
    overdueAmount: 0,
    due7DaysAmount: 120000,
    disputesAmount: 0,
    maxDaysOverdue: 0,
    hasAiInsights: false,
    accountSummary: 'No overdue balance. Within normal payment window.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: '3217iii',
    customerNumber: '3217',
    customerName: 'Grand Rapids Wmns Hlth Obgyn',
    customerContact: 'Dr. Carol Grant',
    contactEmail: 'c.grant@grandrpds.com',
    assignedTo: 'Sarah Kim',
    priority: 3,
    amountOutstanding: 161971,
    amountOutstandingEur: 161971,
    currency: 'EUR',
    dsoPerCustomer: 0,
    maxArrearsDays: -34,
    maxPredDelayed: 20,
    lastCommDate: '12/11/2025',
    creditLimit: 300000,
    creditExposure: 180000,
    creditUtilizationRate: 60.0,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 0,
    due7DaysCount: 2,
    disputesCount: 0,
    overdueAmount: 0,
    due7DaysAmount: 50000,
    disputesAmount: 0,
    maxDaysOverdue: 0,
    hasAiInsights: false,
    accountSummary: 'Not yet overdue. Good standing customer.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: '93667jjj',
    customerNumber: '93667',
    customerName: 'TriHealth Inc',
    customerContact: 'Robert Tri',
    contactEmail: 'r.tri@trihealth.com',
    assignedTo: 'Jordan Lee',
    priority: 3,
    amountOutstanding: 900679,
    amountOutstandingEur: 900679,
    currency: 'USD',
    dsoPerCustomer: 0,
    maxArrearsDays: -5,
    maxPredDelayed: 6,
    lastCommDate: '12/11/2025',
    creditLimit: 1200000,
    creditExposure: 950000,
    creditUtilizationRate: 79.2,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 0,
    due7DaysCount: 6,
    disputesCount: 0,
    overdueAmount: 0,
    due7DaysAmount: 300000,
    disputesAmount: 0,
    maxDaysOverdue: 0,
    hasAiInsights: false,
    accountSummary: 'Large balance not yet due. High credit utilization — monitor closely.',
    recommendedAction: '—',
    hitlPending: false,
  },
  {
    id: '39978ddd',
    customerNumber: '39978',
    customerName: 'Springfield Clinic',
    customerContact: 'Tom Bradley',
    contactEmail: 't.bradley@springfieldclinic.com',
    assignedTo: 'Sarah Kim',
    priority: 3,
    amountOutstanding: 252495,
    amountOutstandingEur: 252495,
    currency: 'USD',
    dsoPerCustomer: 0,
    maxArrearsDays: -25,
    maxPredDelayed: 5,
    lastCommDate: '12/10/2025',
    creditLimit: 600000,
    creditExposure: 350000,
    creditUtilizationRate: 58.3,
    blockedOrdersCount: 0,
    blockedOrdersAmount: 0,
    overdueCount: 0,
    due7DaysCount: 4,
    disputesCount: 0,
    overdueAmount: 0,
    due7DaysAmount: 120000,
    disputesAmount: 0,
    maxDaysOverdue: 0,
    hasAiInsights: true,
    accountSummary: 'No overdue balance. $120K due in 7 days — within normal payment window. Good standing customer.',
    recommendedAction: '—',
    hitlPending: false,
  },
];

export const COMMUNICATIONS: BayerCommunication[] = [
  // Northern Ohio Medical Spc LLC — real thread from mock/data.json
  {
    id: 'a1000055',
    customerId: '06f6d03a',
    direction: 'outbound',
    subject: 'URGENT: Northern Ohio Medical - 113 Days Overdue',
    body: 'Dear Dr. Patterson, I\'m writing with urgent concern about Northern Ohio Medical Spc LLC\'s account, which shows $87,988.04 in invoices that are 113 days past due. This significant aging requires immediate attention.',
    sentDate: '2025-11-18T08:00:00Z',
    fromEmail: 'vimlesh.kumar@nf3q.onmicrosoft.com',
    toEmail: 'james.patterson@northernohiomedical.com',
    sentiment: 'negative',
    summary: 'Urgent escalation for 113-day overdue account',
  },
  {
    id: 'a1000056',
    customerId: '06f6d03a',
    direction: 'inbound',
    subject: 'RE: URGENT: Northern Ohio Medical - Investigation Underway',
    body: 'Hi Vimlesh, I apologize for this situation. We\'re investigating why these invoices weren\'t processed. Our AP team is researching now and I\'ll have an update for you by end of day tomorrow.',
    sentDate: '2025-11-20T15:20:00Z',
    fromEmail: 'james.patterson@northernohiomedical.com',
    toEmail: 'vimlesh.kumar@nf3q.onmicrosoft.com',
    sentiment: 'neutral',
    summary: 'Customer acknowledges issue, investigating internally',
  },
  {
    id: 'a1000057',
    customerId: '06f6d03a',
    direction: 'outbound',
    subject: 'RE: Investigation - Urgent Response Required',
    body: 'Dear Dr. Patterson, Thank you for your response. Given the amount and aging, I can hold escalation for 48 hours while you investigate. Please provide: root cause, concrete payment timeline, point of contact.',
    sentDate: '2025-11-21T09:00:00Z',
    fromEmail: 'vimlesh.kumar@nf3q.onmicrosoft.com',
    toEmail: 'james.patterson@northernohiomedical.com',
    sentiment: 'neutral',
    summary: 'Conditional hold on escalation pending investigation details',
  },
  {
    id: 'a1000058',
    customerId: '06f6d03a',
    direction: 'inbound',
    subject: 'RE: Investigation Results - Payment Plan Proposal',
    body: 'Hi Vimlesh, We identified the issue — several invoices were stuck in our approval workflow due to a system glitch. We propose: $45,000 payment this Friday (Nov 29), remaining balance by December 15.',
    sentDate: '2025-11-26T13:45:00Z',
    fromEmail: 'james.patterson@northernohiomedical.com',
    toEmail: 'vimlesh.kumar@nf3q.onmicrosoft.com',
    sentiment: 'positive',
    summary: 'Customer identifies root cause, proposes payment plan',
  },
  {
    id: 'a1000059',
    customerId: '06f6d03a',
    direction: 'outbound',
    subject: 'Payment Plan Follow-up',
    body: 'Dear Dr. Patterson, I\'m following up on the payment plan we discussed. We have not yet received the $45,000 payment that was expected last Friday. Please provide an immediate status update.',
    sentDate: '2025-12-05T08:30:00Z',
    fromEmail: 'vimlesh.kumar@nf3q.onmicrosoft.com',
    toEmail: 'james.patterson@northernohiomedical.com',
    sentiment: 'negative',
    summary: 'Follow-up on missed payment commitment',
  },
  // DuPage Medical Group Ltd
  {
    id: 'c001',
    customerId: 'fe362849',
    direction: 'outbound',
    subject: 'Payment Reminder — Outstanding Balance $1,010,456',
    body: 'Dear Dr. Marin, I hope this message finds you well. I\'m writing to follow up on DuPage Medical Group Ltd\'s outstanding balance of $1,010,456.',
    sentDate: '2025-12-09T09:15:00Z',
    fromEmail: 'jordan.lee@bayer.com',
    toEmail: 'an_marin@outlook.com',
    sentiment: 'neutral',
    summary: 'Payment reminder for $1M overdue balance',
  },
  {
    id: 'c002',
    customerId: 'fe362849',
    direction: 'inbound',
    subject: 'Re: Payment Reminder — Outstanding Balance',
    body: 'Dear Jordan, Thank you for your note. We are processing the invoices and expect payment within 2 weeks.',
    sentDate: '2025-12-01T14:30:00Z',
    fromEmail: 'an_marin@outlook.com',
    toEmail: 'jordan.lee@bayer.com',
    sentiment: 'positive',
    summary: 'Customer acknowledges debt, promises payment in 2 weeks',
  },
  // Norton Healthcare
  {
    id: 'c003',
    customerId: '170758cc',
    direction: 'outbound',
    subject: 'Urgent: Overdue Balance — Norton Healthcare',
    body: 'Dear Mr. Norton, This is a follow-up regarding your outstanding balance of $82,011.',
    sentDate: '2025-12-05T10:00:00Z',
    fromEmail: 'jordan.lee@bayer.com',
    toEmail: 'j.norton@nortonhealthcare.com',
    sentiment: 'negative',
    summary: 'Urgent escalation — no response to prior outreach',
  },
  // Institut Bergonié
  {
    id: 'c004',
    customerId: '12614fff',
    direction: 'outbound',
    subject: 'Payment Reminder — Institut Bergonié',
    body: 'Dear Ms. Dupont, I am writing regarding your outstanding balance. The agent has drafted an email for your review.',
    sentDate: '2025-12-11T08:00:00Z',
    fromEmail: 'sarah.kim@bayer.com',
    toEmail: 'm.dupont@bergonie.fr',
    sentiment: 'neutral',
    summary: 'AI-drafted payment reminder awaiting HITL approval',
  },
];

export const INVOICES: BayerInvoice[] = [
  // Northern Ohio Medical Spc LLC — real data from mock/data.json
  { id: 'ca824f08', customerId: '06f6d03a', documentNumber: '6044865005', documentTypeText: 'Invoice', amount: 9595.60, currency: 'USD', dueDate: '2025-08-05', isOverdue: true, daysOverdue: 113 },
  { id: 'bc7cd960', customerId: '06f6d03a', documentNumber: '6044891771', documentTypeText: 'Invoice', amount: 14393.40, currency: 'USD', dueDate: '2025-11-17', isOverdue: true, daysOverdue: 9 },
  { id: '24425218', customerId: '06f6d03a', documentNumber: '6044891772', documentTypeText: 'Invoice', amount: 9352.70, currency: 'USD', dueDate: '2025-11-17', isOverdue: true, daysOverdue: 9 },
  { id: 'fe90527e', customerId: '06f6d03a', documentNumber: '6044891773', documentTypeText: 'Invoice', amount: 19191.20, currency: 'USD', dueDate: '2025-11-17', isOverdue: true, daysOverdue: 9 },
  { id: '98b23165', customerId: '06f6d03a', documentNumber: '6044891774', documentTypeText: 'Invoice', amount: 6668.34, currency: 'USD', dueDate: '2025-11-17', isOverdue: true, daysOverdue: 9 },
  { id: '8d81c845', customerId: '06f6d03a', documentNumber: '6044904883', documentTypeText: 'Invoice', amount: 9595.60, currency: 'USD', dueDate: '2026-01-05', isOverdue: false, daysOverdue: 0 },
  { id: '8cb28b04', customerId: '06f6d03a', documentNumber: '6044905287', documentTypeText: 'Invoice', amount: 19191.20, currency: 'USD', dueDate: '2026-01-06', isOverdue: false, daysOverdue: 0 },
  // DuPage Medical Group Ltd
  { id: 'inv001', customerId: 'fe362849', documentNumber: '6044865001', documentTypeText: 'Invoice', amount: 245000, currency: 'USD', dueDate: '2025-10-15', isOverdue: true, daysOverdue: 49 },
  { id: 'inv002', customerId: 'fe362849', documentNumber: '6044865002', documentTypeText: 'Invoice', amount: 380000, currency: 'USD', dueDate: '2025-10-01', isOverdue: true, daysOverdue: 63 },
  { id: 'inv003', customerId: 'fe362849', documentNumber: '6044865003', documentTypeText: 'Invoice', amount: 125000, currency: 'USD', dueDate: '2025-09-30', isOverdue: true, daysOverdue: 64 },
  { id: 'inv004', customerId: 'fe362849', documentNumber: '6044865004', documentTypeText: 'Invoice', amount: 260456, currency: 'USD', dueDate: '2025-11-20', isOverdue: true, daysOverdue: 14 },
  // Norton Healthcare
  { id: 'inv005', customerId: '170758cc', documentNumber: '6044866001', documentTypeText: 'Invoice', amount: 40000, currency: 'USD', dueDate: '2025-10-20', isOverdue: true, daysOverdue: 44 },
  { id: 'inv006', customerId: '170758cc', documentNumber: '6044866002', documentTypeText: 'Invoice', amount: 22011, currency: 'USD', dueDate: '2025-09-15', isOverdue: true, daysOverdue: 79 },
  { id: 'inv007', customerId: '170758cc', documentNumber: '6044866003', documentTypeText: 'Invoice', amount: 20000, currency: 'USD', dueDate: '2025-10-28', isOverdue: true, daysOverdue: 36 },
  // Institut Bergonié
  { id: 'inv008', customerId: '12614fff', documentNumber: '6044867001', documentTypeText: 'Invoice', amount: 50000, currency: 'USD', dueDate: '2025-09-01', isOverdue: true, daysOverdue: 133 },
  { id: 'inv009', customerId: '12614fff', documentNumber: '6044867002', documentTypeText: 'Invoice', amount: 46671, currency: 'USD', dueDate: '2025-10-01', isOverdue: true, daysOverdue: 72 },
];

export const ACTIVITIES: BayerActivity[] = [
  // Northern Ohio Medical — real AgentRuns + AccountHistory from mock/data.json
  { id: 'a1000001-0005', customerId: '06f6d03a', timestamp: '2026-02-04T08:15:00Z', description: 'Account reviewed — awaiting HITL approval to proceed', performedBy: 'AI Agent' },
  { id: 'a1000001-0004', customerId: '06f6d03a', timestamp: '2026-02-03T22:25:00Z', description: 'Agent run failed — FSCM contact record creation failed due to service timeout', performedBy: 'AI Agent' },
  { id: 'a1000001-0001', customerId: '06f6d03a', timestamp: '2026-02-02T14:30:00Z', description: 'Payment reminder email sent successfully — $87,988.04 overdue, 113 days past due', performedBy: 'Jordan Lee' },
  { id: 'a1000001-0002', customerId: '06f6d03a', timestamp: '2026-02-01T09:15:00Z', description: 'Account reviewed — comprehensive outreach scheduled for Feb 2', performedBy: 'Jordan Lee' },
  { id: 'a1000001-0003', customerId: '06f6d03a', timestamp: '2026-01-31T16:45:00Z', description: 'Initial account assessment — outreach strategy under development', performedBy: 'Jordan Lee' },
  { id: 'b1000082', customerId: '06f6d03a', timestamp: '2025-12-05T08:30:00Z', description: 'Follow-up sent — initial payment not received on agreed date', performedBy: 'Vimlesh Kumar' },
  { id: 'b1000081', customerId: '06f6d03a', timestamp: '2025-11-26T13:45:00Z', description: 'Customer identified system glitch as root cause, proposed payment plan', performedBy: 'System' },
  { id: 'b1000080', customerId: '06f6d03a', timestamp: '2025-11-21T09:00:00Z', description: '48-hour hold on escalation granted pending investigation', performedBy: 'Vimlesh Kumar' },
  { id: 'b1000079', customerId: '06f6d03a', timestamp: '2025-11-20T15:20:00Z', description: 'Customer investigating invoice processing delay — no payment yet', performedBy: 'System' },
  { id: 'b1000078', customerId: '06f6d03a', timestamp: '2025-11-18T08:00:00Z', description: 'Urgent escalation sent — 113 days overdue, $87K balance', performedBy: 'Vimlesh Kumar' },
  { id: 'b1000084', customerId: '06f6d03a', timestamp: '2025-11-08T10:30:00Z', description: 'AI Agent flagged high-risk — significant aging detected', performedBy: 'AI Agent' },
  // DuPage Medical Group Ltd
  { id: 'act001', customerId: 'fe362849', timestamp: '2025-12-09T09:15:00Z', description: 'Payment reminder email sent', performedBy: 'Jordan Lee' },
  { id: 'act002', customerId: 'fe362849', timestamp: '2025-12-01T14:30:00Z', description: 'Customer responded — payment promised in 2 weeks', performedBy: 'System' },
  { id: 'act003', customerId: 'fe362849', timestamp: '2025-12-05T08:00:00Z', description: 'AI agent analyzed account — HITL approval requested for follow-up email', performedBy: 'AI Agent' },
  // Norton Healthcare
  { id: 'act004', customerId: '170758cc', timestamp: '2025-11-20T11:00:00Z', description: 'First payment reminder sent', performedBy: 'Jordan Lee' },
  { id: 'act005', customerId: '170758cc', timestamp: '2025-11-30T09:00:00Z', description: 'Second reminder sent — no response', performedBy: 'Jordan Lee' },
  { id: 'act006', customerId: '170758cc', timestamp: '2025-12-03T10:00:00Z', description: 'Escalation email sent — AI agent flagged for manager review', performedBy: 'AI Agent' },
  // Institut Bergonié
  { id: 'act007', customerId: '12614fff', timestamp: '2025-12-11T08:00:00Z', description: 'AI agent drafted payment reminder — awaiting HITL approval to send', performedBy: 'AI Agent' },
  // UPenn
  { id: 'act008', customerId: '121437bb', timestamp: '2025-12-06T10:00:00Z', description: 'AI agent recommends phone call — HITL approval requested', performedBy: 'AI Agent' },
  // Cache Valley
  { id: 'act009', customerId: '19136ccc', timestamp: '2025-12-08T09:00:00Z', description: 'AI agent recommends reviewing collections strategy — HITL approval requested', performedBy: 'AI Agent' },
];
